{% set name = "pcre2" %}
{% set version = "10.34" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://ftp.pcre.org/pub/pcre/{{ name }}-{{ version }}.tar.bz2
  sha256: 74c473ffaba9e13db6951fd146e0143fe9887852ce73406a03277af1d9b798ca

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # https://abi-laboratory.pro/index.php?view=timeline&l=pcre2
    - {{ pin_subpackage("pcre2", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja
  host:
    - bzip2
    - libedit
    - zlib

test:
  commands:
    - pcre2test --version
    - pcre2grep --version
    - pcre2-config --version
    - test -f ${PREFIX}/include/pcre2.h
    - test -f ${PREFIX}/include/pcre2posix.h
    - test -f ${PREFIX}/lib/libpcre2-posix${SHLIB_EXT}     # [not win]

about:
  home: http://www.pcre.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENCE
  summary: 'Regular expression pattern matching using Perl 5 syntax and semantics.'
  description: |
    The PCRE library is a set of functions that implement regular expression pattern matching
    using the same syntax and semantics as Perl 5. PCRE has its own native API, as well as a set of
    wrapper functions that correspond to the POSIX regular expression API. The PCRE library is
    free, even for building proprietary software.
  doc_url: http://www.pcre.org/current/doc/html/

extra:
  recipe-maintainers:
    - dfornika
    - mariusvniekerk
    - xhochy
